const NAME_AND_PASSWORD_IS_REQUIRE = 'name_and_password_is_require'
const USER_NAME_IS_EXIST = 'username_is_exist'
const USER_IS_NOT_EXIST = 'user_is_not_exist'
const PASSWORD_IS_INCORRECT = 'password_is_incorrect'
const TOKEN_IS_MISSING = 'TOKEN_IS_MISSING'
const TOKEN_IS_INVALID = 'TOKEN_IS_INVALID'
const AMOUNT_IS_INVALID = 'AMOUNT_IS_INVALID'
const CDKEY_IS_MISSING = 'CDKEY_IS_MISSING'
const CDKEY_IS_INVALID = 'CDKEY_IS_INVALID'
const STADIUM_ID_IS_REQUIRED = 'STADIUM_ID_IS_REQUIRED'
const ORDER_NO_IS_INVALID = 'ORDER_NO_IS_INVALID'
const FILE_IS_REQUIRED = 'FILE_IS_REQUIRED'
const FILE_IS_NOT_FOUND = 'FILE_IS_NOT_FOUND'

module.exports = {
  NAME_AND_PASSWORD_IS_REQUIRE,
  USER_NAME_IS_EXIST,
  USER_IS_NOT_EXIST,
  PASSWORD_IS_INCORRECT,
  TOKEN_IS_INVALID,
  TOKEN_IS_MISSING,
  AMOUNT_IS_INVALID,
  CDKEY_IS_MISSING,
  CDKEY_IS_INVALID,
  STADIUM_ID_IS_REQUIRED,
  ORDER_NO_IS_INVALID,
  FILE_IS_REQUIRED,
  FILE_IS_NOT_FOUND,
}
